#!/bin/sh

mariadb -e "CREATE DATABASE wordpress;"
mariadb -e "CREATE USER ${MARIADB_USER}@'localhost' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO ${MARIADB_USER}@'localhost' WITH GRANT OPTION;
CREATE USER ${MARIADB_USER}@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO ${MARIADB_USER}@'%' WITH GRANT OPTION;FLUSH PRIVILEGES;"
mariadb -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';FLUSH PRIVILEGES;"
