version: '3.9'

networks:
  docker-network:
    name: docker-network
    driver: bridge

services:
  postgres:
    container_name: $POSTGRES_HOST
    image: postgres
    ports:
      - 5432
    networks:
      - docker-network
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: on-failure
  nestjs:
    depends_on:
      - postgres
    container_name: nestjs
    build: ./nest-back
    ports:
      - $VITE_NESTJS_PORT:$VITE_NESTJS_PORT
    networks:
      - docker-network
    env_file:
      - ./.env
    restart: on-failure
  sveltekit:
    depends_on:
      - nestjs
    container_name: sveltekit
    build:
      context: ./svelte-front
      args:
        - VITE_HOST=$VITE_HOST
        - VITE_NESTJS_PORT=$VITE_NESTJS_PORT
        - SVELTEKIT_PORT=$SVELTEKIT_PORT
        - VITE_INTRA_CLIENT_UID=$VITE_INTRA_CLIENT_UID
    ports:
     - 80:$SVELTEKIT_PORT
    networks:
      - docker-network
    restart: on-failure
