version: '3.9'

volumes:
  db:
    name: db
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/lwyss/data/db'
  wp:
    name: wp
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/lwyss/data/wp'

networks:
  docker-network:
    name: docker-network
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - docker-network
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp:/www
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/wordpress
    depends_on:
      - mariadb
    networks:
      - docker-network
    restart: always
  bonus:
    container_name: bonus
    build: ./requirements/bonus
    ports:
      - 80:80
    networks:
      - docker-network
    restart: always
