version: '3.9'

volumes:
  db:
    name: db
  data:
    name: data

networks:
  docker-network:
    name: docker-network

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    volumes:
    - db:/db
    networks:
    - docker-network
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    networks:
      - docker-network
  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
    - data:/data
    networks:
    - docker-network
    depends_on:
      - mariadb
