version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    restart: always
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
  wordpress:
    container_name: wordpress
    build: ./wordpress
    depends_on:
      - mariadb
    restart: always

volumes:
  db_data: {}
  wp_data: {}
